help:
	@echo "This makefile for repo-level activity"

create-practice:
	@echo "Creating practice"
	mkdir demo-practice

remove-practice:
	rm -rf demo-practice

#mkdir demo-practice
#mkdir demo-practice/src
#mkdir demo-practice/tests
#mkdir demo-practice/docs
#touch demo-practice/README.md