create-structure:
	mkdir src tests docs
	touch README.md setup.py requirements.txt
	touch docs/DOMAIN.md
	touch src/.gitkeep tests/.gitkeep

test-pytest:
	python3 -m pytest

install-dep:
	pip install -r requirements.txt

install:
	pip install -e .